name: Coupang PO Crawler

on:
  schedule:
    # 월~금 (1-5), 한국 시간 기준으로 9, 11, 13, 15, 17, 19시에 실행
    # 깃허브는 영국 시간(UTC)을 쓰기 때문에 한국 시간에서 9를 빼주어야 해요.
    - cron: '0 0,2,4,6,8,10 * * 1-5'
  workflow_dispatch: # 버튼을 눌러서 수동으로도 켤 수 있게 해주는 기능이에요

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 파일들 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치하기
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 필요한 도구들 설치하기 (requirements.txt)
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: 파이썬 로봇 실행하기
        env:
          # 깃허브 설정(Secrets)에 저장해 둔 비밀번호들을 파이썬으로 넘겨줍니다.
          COUPANG_ID_1: ${{ secrets.COUPANG_ID_1 }}
          COUPANG_PW_1: ${{ secrets.COUPANG_PW_1 }}
          COUPANG_ID_2: ${{ secrets.COUPANG_ID_2 }}
          COUPANG_PW_2: ${{ secrets.COUPANG_PW_2 }}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        run: python main.py
        
      - name: 에러 스크린샷 구출하기
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: '*.png'        
          
